name: peak_health_task
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_emoji_keyboard: ^0.1.3
  #charts_flutter: ^0.11.0
  image_picker: ^0.6.7+22
  emoji_picker: ^0.1.0
  shared_preferences: ^0.5.5
  flutter_keyboard_visibility: ^3.2.2
  full_screen_menu: ^0.1.2
  font_awesome_flutter: ^8.5.0
  #syncfusion_flutter_gauges: ^18.2.44
  #charts_flutter: ^0.8.1
  #syncfusion_flutter_charts: ^17.3.26

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - image/Group 507.png
    - image/Group 508.png
    - image/Group 509.png
    - image/Group 510.png
    - image/Group 511.png
    - image/1.png
    - image/2.png
    - image/3.png
    - image/4.png
    - image/5.png
    - image/Group 504.png
    - image/Icon awesome-angry.png
    - image/Icon awesome-sad-tear.png
    - image/Icon ionic-ios-happy.png
    - image/Icon ionic-ios-sad.png
    - image/Icon ionic-ios-sad-1.png
    - image/Group 515.png
    - image/Group 516.png
    - image/Group 517.png
    - image/Group 518.png
    - image/Group 519.png
    - image/lk.png
    - image/kl.png
    - image/j.png
    - image/kj.png
    - image/jk.png
    - image/2Icon awesome-angry.png
    - image/2Icon awesome-sad-tear.png
    - image/Group 520.png
    - image/Group 521.png
    - image/Group 522.png
    - image/darkgreen-box.png
    - image/lightgreen-box.png
    - image/orange-box.png
    - image/red-box.png
    - image/yellow-box.png
    - image/five.png
    - image/four.png
    - image/one.png
    - image/three.png
    - image/two.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
         # weight: 700
          #style: italic

    #- family: RobotoMono
     # fonts:
      #  - asset: fonts/RobotoMono.ttf
      #  - asset: fonts/RobotoMono_Bold.ttf
      #    weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
